//
//Miguel Rodríguez
//

p5.disableFriendlyErrors = true
const WIDTH = 600
const HEIGHT = 600

let state = 'painting'

// A canvas is composed of NxN cells that are composed of MxM pixels

let canvas = []         //canvas where you paint
let numberOfCells = 3   //numberOfCells x numberOfCells
let pixelsPerCell = 10
let canvasSize = numberOfCells * pixelsPerCell  //number of pixels
let pixelSize = WIDTH / canvasSize
let cellSize = WIDTH / numberOfCells

let curColor
let curSize = 0

let panel, pColPick, pSizeSel, pSelCanvSize, pBucket, pEraser

let brushes = []

let wfc
let wfcSize = 3

function initCanvasDebug(){
    canvas = [
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null,
            [
                255,
                46,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            [
                255,
                46,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            [
                132,
                255,
                0,
                255
            ],
            [
                132,
                255,
                0,
                255
            ],
            [
                132,
                255,
                0,
                255
            ],
            [
                132,
                255,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            [
                0,
                124,
                252,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            [
                255,
                46,
                0,
                255
            ],
            [
                255,
                46,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            [
                132,
                255,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            [
                0,
                124,
                252,
                255
            ],
            null,
            null,
            [
                0,
                124,
                252,
                255
            ],
            null,
            null,
            null
        ],
        [
            null,
            null,
            [
                255,
                46,
                0,
                255
            ],
            [
                255,
                46,
                0,
                255
            ],
            [
                255,
                46,
                0,
                255
            ],
            [
                255,
                46,
                0,
                255
            ],
            [
                255,
                46,
                0,
                255
            ],
            [
                255,
                46,
                0,
                255
            ],
            [
                255,
                46,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            [
                132,
                255,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            [
                0,
                124,
                252,
                255
            ],
            null,
            null,
            [
                0,
                124,
                252,
                255
            ],
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            [
                132,
                255,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            [
                0,
                124,
                252,
                255
            ],
            [
                0,
                124,
                252,
                255
            ],
            [
                0,
                124,
                252,
                255
            ],
            [
                0,
                124,
                252,
                255
            ],
            [
                0,
                124,
                252,
                255
            ],
            null,
            null
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            [
                132,
                255,
                0,
                255
            ],
            [
                132,
                255,
                0,
                255
            ],
            [
                132,
                255,
                0,
                255
            ],
            [
                132,
                255,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            [
                0,
                124,
                252,
                255
            ],
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            [
                0,
                124,
                252,
                255
            ],
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            [
                255,
                177,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            [
                0,
                0,
                0,
                0
            ],
            [
                0,
                0,
                0,
                0
            ],
            [
                0,
                0,
                0,
                0
            ],
            [
                0,
                0,
                0,
                0
            ],
            [
                0,
                0,
                0,
                0
            ],
            [
                0,
                0,
                0,
                0
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            [
                255,
                177,
                0,
                255
            ],
            [
                255,
                177,
                0,
                255
            ],
            null,
            null,
            null,
            [
                255,
                177,
                0,
                255
            ],
            null,
            null,
            null,
            [
                0,
                188,
                12,
                255
            ],
            [
                0,
                188,
                12,
                255
            ],
            [
                0,
                188,
                12,
                255
            ],
            [
                0,
                188,
                12,
                255
            ],
            [
                0,
                188,
                12,
                255
            ],
            null,
            [
                0,
                0,
                0,
                0
            ],
            [
                0,
                0,
                0,
                0
            ],
            null,
            null,
            null,
            null,
            [
                30,
                0,
                252,
                255
            ],
            [
                30,
                0,
                252,
                255
            ],
            [
                30,
                0,
                252,
                255
            ],
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            [
                255,
                177,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            [
                255,
                177,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            [
                0,
                188,
                12,
                255
            ],
            null,
            [
                0,
                0,
                0,
                0
            ],
            [
                0,
                188,
                12,
                255
            ],
            null,
            [
                0,
                188,
                12,
                255
            ],
            [
                0,
                0,
                0,
                0
            ],
            null,
            null,
            null,
            [
                30,
                0,
                252,
                255
            ],
            [
                30,
                0,
                252,
                255
            ],
            null,
            [
                30,
                0,
                252,
                255
            ],
            [
                30,
                0,
                252,
                255
            ],
            [
                30,
                0,
                252,
                255
            ],
            [
                30,
                0,
                252,
                255
            ],
            null
        ],
        [
            null,
            null,
            [
                255,
                177,
                0,
                255
            ],
            null,
            null,
            null,
            [
                255,
                177,
                0,
                255
            ],
            [
                255,
                177,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            [
                0,
                188,
                12,
                255
            ],
            null,
            null,
            [
                0,
                188,
                12,
                255
            ],
            null,
            [
                0,
                188,
                12,
                255
            ],
            [
                0,
                0,
                0,
                0
            ],
            null,
            null,
            null,
            [
                30,
                0,
                252,
                255
            ],
            null,
            null,
            [
                30,
                0,
                252,
                255
            ],
            null,
            null,
            [
                30,
                0,
                252,
                255
            ],
            null
        ],
        [
            null,
            null,
            [
                255,
                177,
                0,
                255
            ],
            [
                255,
                177,
                0,
                255
            ],
            [
                255,
                177,
                0,
                255
            ],
            [
                255,
                177,
                0,
                255
            ],
            [
                255,
                177,
                0,
                255
            ],
            [
                255,
                177,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            [
                0,
                188,
                12,
                255
            ],
            null,
            null,
            [
                0,
                188,
                12,
                255
            ],
            [
                0,
                188,
                12,
                255
            ],
            [
                0,
                188,
                12,
                255
            ],
            null,
            null,
            null,
            null,
            [
                30,
                0,
                252,
                255
            ],
            null,
            null,
            [
                30,
                0,
                252,
                255
            ],
            [
                30,
                0,
                252,
                255
            ],
            [
                30,
                0,
                252,
                255
            ],
            [
                30,
                0,
                252,
                255
            ],
            null
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            [
                255,
                177,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            [
                0,
                188,
                12,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            [
                30,
                0,
                252,
                255
            ],
            [
                30,
                0,
                252,
                255
            ],
            [
                30,
                0,
                252,
                255
            ],
            [
                30,
                0,
                252,
                255
            ],
            [
                30,
                0,
                252,
                255
            ],
            [
                30,
                0,
                252,
                255
            ],
            null,
            null
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            [
                255,
                177,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            [
                0,
                0,
                0,
                0
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            [
                254,
                255,
                0,
                255
            ],
            [
                0,
                0,
                0,
                0
            ],
            null,
            null,
            null,
            [
                0,
                0,
                0,
                0
            ],
            [
                254,
                255,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            [
                196,
                0,
                252,
                255
            ],
            [
                196,
                0,
                252,
                255
            ],
            [
                196,
                0,
                252,
                255
            ],
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            [
                254,
                255,
                0,
                255
            ],
            null,
            [
                0,
                0,
                0,
                0
            ],
            [
                254,
                255,
                0,
                255
            ],
            [
                0,
                0,
                0,
                0
            ],
            [
                0,
                0,
                0,
                0
            ],
            [
                254,
                255,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            [
                0,
                255,
                183,
                255
            ],
            [
                0,
                255,
                183,
                255
            ],
            [
                0,
                255,
                183,
                255
            ],
            [
                0,
                255,
                183,
                255
            ],
            [
                0,
                255,
                183,
                255
            ],
            null,
            null,
            [
                196,
                0,
                252,
                255
            ],
            [
                196,
                0,
                252,
                255
            ],
            null,
            [
                196,
                0,
                252,
                255
            ],
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            [
                254,
                255,
                0,
                255
            ],
            [
                0,
                0,
                0,
                0
            ],
            [
                254,
                255,
                0,
                255
            ],
            [
                254,
                255,
                0,
                255
            ],
            null,
            [
                0,
                0,
                0,
                0
            ],
            [
                254,
                255,
                0,
                255
            ],
            null,
            null,
            null,
            [
                0,
                255,
                183,
                255
            ],
            [
                0,
                255,
                183,
                255
            ],
            null,
            [
                0,
                255,
                183,
                255
            ],
            null,
            null,
            [
                0,
                255,
                183,
                255
            ],
            null,
            null,
            [
                196,
                0,
                252,
                255
            ],
            null,
            null,
            [
                196,
                0,
                252,
                255
            ],
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            [
                254,
                255,
                0,
                255
            ],
            [
                0,
                0,
                0,
                0
            ],
            [
                254,
                255,
                0,
                255
            ],
            [
                254,
                255,
                0,
                255
            ],
            null,
            null,
            [
                254,
                255,
                0,
                255
            ],
            null,
            null,
            null,
            [
                0,
                255,
                183,
                255
            ],
            null,
            null,
            [
                0,
                255,
                183,
                255
            ],
            null,
            null,
            [
                0,
                255,
                183,
                255
            ],
            null,
            null,
            [
                196,
                0,
                252,
                255
            ],
            [
                196,
                0,
                252,
                255
            ],
            null,
            [
                196,
                0,
                252,
                255
            ],
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            [
                254,
                255,
                0,
                255
            ],
            [
                254,
                255,
                0,
                255
            ],
            [
                0,
                0,
                0,
                0
            ],
            [
                0,
                0,
                0,
                0
            ],
            [
                254,
                255,
                0,
                255
            ],
            null,
            [
                254,
                255,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            [
                0,
                255,
                183,
                255
            ],
            [
                0,
                255,
                183,
                255
            ],
            [
                0,
                255,
                183,
                255
            ],
            [
                0,
                255,
                183,
                255
            ],
            null,
            null,
            null,
            [
                196,
                0,
                252,
                255
            ],
            [
                196,
                0,
                252,
                255
            ],
            [
                196,
                0,
                252,
                255
            ],
            [
                196,
                0,
                252,
                255
            ],
            [
                196,
                0,
                252,
                255
            ],
            [
                196,
                0,
                252,
                255
            ],
            null,
            null
        ],
        [
            null,
            null,
            [
                254,
                255,
                0,
                255
            ],
            [
                254,
                255,
                0,
                255
            ],
            null,
            [
                0,
                0,
                0,
                0
            ],
            [
                254,
                255,
                0,
                255
            ],
            [
                254,
                255,
                0,
                255
            ],
            [
                254,
                255,
                0,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            [
                0,
                255,
                183,
                255
            ],
            [
                0,
                255,
                183,
                255
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            [
                0,
                0,
                0,
                0
            ],
            [
                0,
                0,
                0,
                0
            ],
            [
                0,
                0,
                0,
                0
            ],
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ]
    ]
}

function initCanvas(){
    numberOfCells = pSelCanvSize.getValue()
    canvasSize = numberOfCells * pixelsPerCell
    pixelSize = WIDTH / canvasSize
    cellSize = WIDTH / numberOfCells

    for(let i = 0; i < canvasSize; i++){
        canvas[i] = []
        for(let j = 0; j < canvasSize; j++){
            canvas[i][j] = undefined
        }
    }
}

function initBrushes(){
    for (let radius = 0; radius <= 10; radius++) {
        let brush = [];
        for (let x = -radius; x <= radius; x++) {
            for (let y = -radius; y <= radius; y++) {
                if (x * x + y * y <= radius * radius) {
                    brush.push([x, y]);
                }
            }
        }
        brushes.push(brush);
    }
}

function keyPressed(){
    if(state == 'generating') wfc.collapse()
}

function setup(){
    createCanvas(WIDTH+300, HEIGHT)
    
    
    panel = new Panel({
        title: 'Wave Function Collapse',
        x: WIDTH,
        w: 300,
        automaticHeight: false
    })
    panel.createText('First paint, then generate')
    panel.createSeparator()
    pSelCanvSize = panel.createNumberPicker('Size of canvas', 2, 7, 1, 3, initCanvas, initCanvas) //slider para number of cells
    panel.createSeparator()
    pColPick = panel.createColorPicker('Color of brush', () => {curColor = pColPick.getColor()})
    pSizeSel = panel.createSlider(0, 10, 0, 'Size of brush', true, () => {curSize = Math.floor(Math.round(pSizeSel.getValue()))})
    pBucket = panel.createCheckbox('Paint bucket', false)
    pEraser = panel.createCheckbox('Eraser', false)
    panel.createSeparator()
    panel.createButton('Clear', initCanvas)
    panel.createSeparator()
    panel.createButton('Generate', generateWFC)

    initBrushes()
    initCanvasDebug()
}

function keyPressed(){
    redraw()
}

function draw(){
    background(0)
    if(state == 'painting'){
        drawCanvas()
        //drawPixelGrid()
        drawGrid()
        drawCursor()
        if(mouseIsPressed && mouseX < WIDTH && mouseY < HEIGHT){
            let i = Math.floor(mouseX / pixelSize)
            let j = Math.floor(mouseY / pixelSize)
            if(!panel.isInteracting) paint(i, j)
        }
    }
    if(state == 'generating'){
        //noLoop()
        wfc.collapse()
        wfc.show()
    }
    push()
    panel.update()
    panel.show()
    pop()
}

function paint(i, j){
    let col = pEraser.isChecked() ? [0,0,0,0] : curColor
    if(!pBucket.isChecked()){
        let brush = brushes[curSize]
        for(let b = 0; b < brush.length; b++){
            let pixelBrush = brush[b]
            let x = i + pixelBrush[0]
            let y = j + pixelBrush[1]
            if(x >= canvasSize || y >= canvasSize || x < 0 || y < 0) continue
            canvas[x][y] = col
        }
    }
    else{
        if(i >= canvasSize || j >= canvasSize || i < 0 || j < 0) return
        let startI = Math.floor(i/pixelsPerCell) * pixelsPerCell
        let startJ = Math.floor(j/pixelsPerCell) * pixelsPerCell
        for(let i = startI; i < startI + pixelsPerCell; i++){
            for(let j = startJ; j < startJ + pixelsPerCell; j++){
                canvas[i][j] = col
            }
        }
    }
}

function drawCanvas(){
    push()
    noStroke()
    for(let i = 0; i < canvasSize; i++){
        for(let j = 0; j < canvasSize; j++){
            if(canvas[i][j] == undefined) fill(0)
            else fill(canvas[i][j])
            rect(i*pixelSize, j*pixelSize, pixelSize, pixelSize)
        }
    }
    pop()
}

function drawGrid(){
    push()
    stroke(215)
    strokeWeight(1)
    for(let i = 0; i < numberOfCells+1; i++){
        line(0, i*cellSize, WIDTH, i*cellSize)
        line(i*cellSize, 0, i*cellSize, HEIGHT)
    }
    pop()
}

function drawPixelGrid(){
    push()
    stroke(120)
    strokeWeight(.5)
    for(let i = 0; i < canvasSize+1; i++){
        line(0, i*pixelSize, WIDTH, i*pixelSize)
        line(i*pixelSize, 0, i*pixelSize, HEIGHT)
    }
    pop()
}

function drawCursor(){
    push()
    let i = Math.floor(mouseX / pixelSize)
    let j = Math.floor(mouseY / pixelSize)
    if(i >= canvasSize || j >= canvasSize) return
    stroke(255)
    strokeWeight(1.5)
    noFill()
    if(!pBucket.isChecked()){
        let radius = (curSize + 1) * pixelSize
        ellipse(i * pixelSize + pixelSize / 2, j * pixelSize + pixelSize / 2, radius * 2)
    }
    else{
        let startI = Math.floor(i/pixelsPerCell) * pixelsPerCell
        let startJ = Math.floor(j/pixelsPerCell) * pixelsPerCell
        strokeWeight(5)
        rect(startI*pixelSize, startJ * pixelSize, cellSize, cellSize)
    }
    pop()
}

function getHoveredCell(){
    if(mouseX > WIDTH || mouseY > HEIGHT) return undefined
    let startI = Math.floor(Math.floor(mouseX/pixelSize) / pixelsPerCell)
    let startJ = Math.floor(Math.floor(mouseY/pixelSize) / pixelsPerCell)
    return [startI, startJ]
}

//i,j, being the cell index
function getCell(i, j){
    return
    let cell = []

    for(let i = 0; i < pixelsPerCell; i++){
        
    }
}

function generateWFC(){
    state = 'generating'
    wfc = new WFC(canvas)
}

function showWFC(){

}